### ISSUE TITLE
Selenium Grid is not respecting timeout values

### ISSUE THREAD

**Issue by bzon** [Accenture/adop-docker-compose#193]
Having a long running selenium test or a test that is running against a page that loads very slow can cause unexpected timeouts.  

To fix this I have to increase the timeout in the selenium node containers SE_OPTS variable.

Example:  
```yaml
SE_OPTS: "-nodeConfig /var/selenium-config/config-chrome.json -browserTimeout 86400 -timeout 86400"
```

```yaml
selenium-node-chrome:
    restart: always
    image: selenium/node-chrome:2.53.0
    environment:
      SE_OPTS: "-nodeConfig /var/selenium-config/config-chrome.json -browserTimeout 86400 -timeout 86400"
      REMOTE_HOST: "http://selenium-node-chrome:5555"
      HUB_PORT_4444_TCP_ADDR: "selenium-hub"
      HUB_PORT_4444_TCP_PORT: "4444"
```

Similar issue: https://github.com/SeleniumHQ/docker-selenium/issues/150
